### ISSUE TITLE
Extra spacing & content in footer

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Jade-Chan-Speed-work-#4]
Extra spacing & content is coming in footer. (all pages)
Preview: 

![image](https://user-images.githubusercontent.com/97726944/165086065-dda1bd21-078c-4597-90d0-bf1d438dd98b.png)

Live: 

![image](https://user-images.githubusercontent.com/97726944/165086117-d5bea5ff-335b-4575-a853-5125114d1bdb.png)

**Comment by devabulabbas** [comment]
Resolved @Shoaibans
